In [1]:
import numpy as np
import pandas as pd

In [2]:
s1617 = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\Bundesliga\D1-1617.csv')

understats = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\understat_per_game.csv')

In [3]:
s1617 = s1617[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR','HTHG','HTAG',
              'HS', 'AS', 'HST','AST','HC','AC', 'HF', 'AF', 'B365H', 'B365A', 'B365D',
               'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']].reset_index(drop=True)

In [4]:
s1617.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,B365D,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA
0,26/08/16,Bayern Munich,Werder Bremen,6,0,H,2,0,27,4,...,10.00,1.11,12.20,27.00,1.11,8.0,21.00,1.12,10.0,22.0
1,27/08/16,Augsburg,Wolfsburg,0,2,A,0,1,13,12,...,3.25,2.85,3.43,2.64,2.70,3.2,2.45,2.75,3.4,2.6
2,27/08/16,Dortmund,Mainz,2,1,H,1,0,17,12,...,5.00,1.37,5.41,9.49,1.36,4.5,7.00,1.33,5.4,9.0
3,27/08/16,Ein Frankfurt,Schalke 04,1,0,H,1,0,11,11,...,3.30,3.39,3.64,2.22,2.88,3.5,2.20,3.25,3.6,2.2
4,27/08/16,FC Koln,Darmstadt,2,0,H,1,0,21,12,...,3.50,1.78,3.72,5.31,1.80,3.4,4.00,1.80,3.6,4.8

In [5]:
s1617['Date'] = pd.to_datetime(s1617['Date'],format="%d/%m/%y")

In [6]:
understats['Date'] = pd.to_datetime(understats['date']).dt.strftime("%Y-%m-%d")
understats['Date'] = pd.to_datetime(understats['Date'])

In [7]:
understats =understats.replace({'team':{'Hamburger SV':'Hamburg','Bayer Leverkusen':'Leverkusen','Eintracht Frankfurt':'Ein Frankfurt',
                           "Borussia M.Gladbach":"M'gladbach",'Hertha Berlin':'Hertha','Mainz 05':'Mainz',
                           'Hannover 96':'Hannover','Borussia Dortmund':'Dortmund','VfB Stuttgart':'Stuttgart',
                           'FC Cologne':'FC Koln', 'RasenBallsport Leipzig':'RB Leipzig','Nuernberg':'Nurnberg',
                           'Fortuna Duesseldorf':'Fortuna Dusseldorf'}})

In [8]:
df = pd.merge(s1617,understats, how='inner',left_on=['Date','HomeTeam'],right_on=['Date','team'])

In [9]:
df.shape

(306, 57)

In [10]:
df.isnull().sum()

Date            0
HomeTeam        0
AwayTeam        0
FTHG            0
FTAG            0
FTR             0
HTHG            0
HTAG            0
HS              0
AS              0
HST             0
AST             0
HC              0
AC              0
HF              0
AF              0
B365H           0
B365A           0
B365D           0
PSH             0
PSD             0
PSA             0
WHH             1
WHD             1
WHA             1
VCH             0
VCD             0
VCA             0
league          0
year            0
h_a             0
xG              0
xGA             0
npxG            0
npxGA           0
deep            0
deep_allowed    0
scored          0
missed          0
xpts            0
result          0
date            0
wins            0
draws           0
loses           0
pts             0
npxGD           0
ppda_coef       0
ppda_att        0
ppda_def        0
oppda_coef      0
oppda_att       0
oppda_def       0
team            0
xG_diff         0
xGA_diff        0
xpts_diff       0
dtype: int64

In [11]:
df.rename(columns = {'xG':"HxG", 'xGA':'AxG','deep':'Hdeep','deep_allowed':'Adeep',
                     'ppda_coef':'Hppda_coef','oppda_coef':'Appda_coef'},inplace=True)

df = df.drop(['npxG','npxGA','scored', 'missed', 'xpts', 'result', 'wins',
              'draws', 'loses', 'pts', 'npxGD', 'ppda_att', 'ppda_def',
              'oppda_att', 'oppda_def', 'team', 'xG_diff', 'xGA_diff',
              'xpts_diff', 'date', 'year','h_a'],axis=1)

In [12]:
#We know that most of the times the books odds are almost the same. So we are going to replace the null values with the
#average of the 3 other sites odds
index = df.loc[df['WHH'].isnull()].index
    
df.loc[index,'WHH'] = (df.loc[index,'B365H'] + df.loc[index,'PSH'] + df.loc[index,'VCH'])/3
df.loc[index,'WHD'] = (df.loc[index,'B365D'] + df.loc[index,'PSD'] + df.loc[index,'VCD'])/3
df.loc[index,'WHA'] = (df.loc[index,'B365A'] + df.loc[index,'PSA'] + df.loc[index,'VCA'])/3

In [13]:
df.isnull().sum()

Date          0
HomeTeam      0
AwayTeam      0
FTHG          0
FTAG          0
FTR           0
HTHG          0
HTAG          0
HS            0
AS            0
HST           0
AST           0
HC            0
AC            0
HF            0
AF            0
B365H         0
B365A         0
B365D         0
PSH           0
PSD           0
PSA           0
WHH           0
WHD           0
WHA           0
VCH           0
VCD           0
VCA           0
league        0
HxG           0
AxG           0
Hdeep         0
Adeep         0
Hppda_coef    0
Appda_coef    0
dtype: int64

In [14]:
# Calculating the average of betting sites odd for each result
avgH = round((df['B365H'] + df['PSH'] + df['WHH'] + df['VCH'])/4,2)
avgD = round((df['B365D'] + df['PSD'] + df['WHD'] + df['VCD'])/4,2)
avgA = round((df['B365A'] + df['PSA'] + df['WHA'] + df['VCA'])/4,2)

df['AVGH'] = avgH
df['AVGD'] = avgD
df['AVGA'] = avgA

#drop the existing columns with betting odds
df = df.drop(['PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 
              'VCD', 'VCA', 'B365H', 'B365D', 'B365A'],axis=1)

In [15]:
df['season'] = '2016/2017'

In [16]:
df.head(9)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,HxG,AxG,Hdeep,Adeep,Hppda_coef,Appda_coef,AVGH,AVGD,AVGA,season
0,2016-08-26,Bayern Munich,Werder Bremen,6,0,H,2,0,27,4,...,4.532630,0.185791,22,0,7.392857,46.400000,1.11,10.05,23.25,2016/2017
1,2016-08-27,Augsburg,Wolfsburg,0,2,A,0,1,13,12,...,0.452708,0.711094,4,2,9.900000,17.214286,2.78,3.32,2.57,2016/2017
2,2016-08-27,Dortmund,Mainz,2,1,H,1,0,17,12,...,1.819840,1.078850,3,5,5.400000,13.028571,1.36,5.08,8.50,2016/2017
3,2016-08-27,Ein Frankfurt,Schalke 04,1,0,H,1,0,11,11,...,1.866880,0.930915,5,3,12.208333,8.956522,3.23,3.51,2.20,2016/2017
4,2016-08-27,FC Koln,Darmstadt,2,0,H,1,0,21,12,...,3.131950,0.558815,5,3,12.785714,17.684211,1.80,3.56,4.72,2016/2017
5,2016-08-27,Hamburg,Ingolstadt,1,1,D,1,0,8,13,...,0.309707,1.207440,2,3,8.000000,7.791667,2.18,3.27,3.50,2016/2017
6,2016-08-27,M'gladbach,Leverkusen,2,1,H,1,0,14,12,...,1.888150,1.110670,3,7,8.720000,6.650000,2.29,3.46,3.08,2016/2017
7,2016-08-28,Hertha,Freiburg,2,1,H,0,0,15,8,...,0.869084,0.360723,10,1,13.875000,27.153846,2.15,3.24,3.61,2016/2017
8,2016-08-28,Hoffenheim,RB Leipzig,2,2,D,0,0,11,23,...,1.156240,2.475260,7,7,6.333333,11.040000,2.50,3.34,2.86,2016/2017

In [17]:
df.loc[df['HomeTeam']=='Bayern Munich','ranking_HT_ls'] = 1
df.loc[df['HomeTeam']=='Dortmund','ranking_HT_ls'] = 2
df.loc[df['HomeTeam']=="Leverkusen",'ranking_HT_ls'] = 3
df.loc[df['HomeTeam']=="M'gladbach",'ranking_HT_ls'] = 4
df.loc[df['HomeTeam']=='Schalke 04','ranking_HT_ls'] = 5
df.loc[df['HomeTeam']=='Mainz','ranking_HT_ls'] = 6
df.loc[df['HomeTeam']=='Hertha','ranking_HT_ls'] = 7
df.loc[df['HomeTeam']=='Wolfsburg','ranking_HT_ls'] = 8
df.loc[df['HomeTeam']=='FC Koln','ranking_HT_ls'] = 9
df.loc[df['HomeTeam']=='Hamburg','ranking_HT_ls'] = 10
df.loc[df['HomeTeam']=='Ingolstadt','ranking_HT_ls'] = 11
df.loc[df['HomeTeam']=='Augsburg','ranking_HT_ls'] = 12
df.loc[df['HomeTeam']=='Werder Bremen','ranking_HT_ls'] = 13
df.loc[df['HomeTeam']=='Darmstadt','ranking_HT_ls'] = 14
df.loc[df['HomeTeam']=='Hoffenheim','ranking_HT_ls'] = 15
df.loc[df['HomeTeam']=='Ein Frankfurt','ranking_HT_ls'] = 16
df.loc[df['HomeTeam']=='Freiburg','ranking_HT_ls'] = -1
df.loc[df['HomeTeam']=='RB Leipzig','ranking_HT_ls'] = -2

In [18]:
df.loc[df['AwayTeam']=='Bayern Munich','ranking_AT_ls'] = 1
df.loc[df['AwayTeam']=='Dortmund','ranking_AT_ls'] = 2
df.loc[df['AwayTeam']=="Leverkusen",'ranking_AT_ls'] = 3
df.loc[df['AwayTeam']=="M'gladbach",'ranking_AT_ls'] = 4
df.loc[df['AwayTeam']=='Schalke 04','ranking_AT_ls'] = 5
df.loc[df['AwayTeam']=='Mainz','ranking_AT_ls'] = 6
df.loc[df['AwayTeam']=='Hertha','ranking_AT_ls'] = 7
df.loc[df['AwayTeam']=='Wolfsburg','ranking_AT_ls'] = 8
df.loc[df['AwayTeam']=='FC Koln','ranking_AT_ls'] = 9
df.loc[df['AwayTeam']=='Hamburg','ranking_AT_ls'] = 10
df.loc[df['AwayTeam']=='Ingolstadt','ranking_AT_ls'] = 11
df.loc[df['AwayTeam']=='Augsburg','ranking_AT_ls'] = 12
df.loc[df['AwayTeam']=='Werder Bremen','ranking_AT_ls'] = 13
df.loc[df['AwayTeam']=='Darmstadt','ranking_AT_ls'] = 14
df.loc[df['AwayTeam']=='Hoffenheim','ranking_AT_ls'] = 15
df.loc[df['AwayTeam']=='Ein Frankfurt','ranking_AT_ls'] = 16
df.loc[df['AwayTeam']=='Freiburg','ranking_AT_ls'] = -1
df.loc[df['AwayTeam']=='RB Leipzig','ranking_AT_ls'] = -2

In [19]:
df.head(9)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,Hdeep,Adeep,Hppda_coef,Appda_coef,AVGH,AVGD,AVGA,season,ranking_HT_ls,ranking_AT_ls
0,2016-08-26,Bayern Munich,Werder Bremen,6,0,H,2,0,27,4,...,22,0,7.392857,46.400000,1.11,10.05,23.25,2016/2017,1.0,13.0
1,2016-08-27,Augsburg,Wolfsburg,0,2,A,0,1,13,12,...,4,2,9.900000,17.214286,2.78,3.32,2.57,2016/2017,12.0,8.0
2,2016-08-27,Dortmund,Mainz,2,1,H,1,0,17,12,...,3,5,5.400000,13.028571,1.36,5.08,8.50,2016/2017,2.0,6.0
3,2016-08-27,Ein Frankfurt,Schalke 04,1,0,H,1,0,11,11,...,5,3,12.208333,8.956522,3.23,3.51,2.20,2016/2017,16.0,5.0
4,2016-08-27,FC Koln,Darmstadt,2,0,H,1,0,21,12,...,5,3,12.785714,17.684211,1.80,3.56,4.72,2016/2017,9.0,14.0
5,2016-08-27,Hamburg,Ingolstadt,1,1,D,1,0,8,13,...,2,3,8.000000,7.791667,2.18,3.27,3.50,2016/2017,10.0,11.0
6,2016-08-27,M'gladbach,Leverkusen,2,1,H,1,0,14,12,...,3,7,8.720000,6.650000,2.29,3.46,3.08,2016/2017,4.0,3.0
7,2016-08-28,Hertha,Freiburg,2,1,H,0,0,15,8,...,10,1,13.875000,27.153846,2.15,3.24,3.61,2016/2017,7.0,-1.0
8,2016-08-28,Hoffenheim,RB Leipzig,2,2,D,0,0,11,23,...,7,7,6.333333,11.040000,2.50,3.34,2.86,2016/2017,15.0,-2.0

In [20]:
df.to_csv('bundesliga-1617.csv', index=False)