In [1]:
import pandas as pd
import numpy as np

In [2]:
s1819 = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\Bundesliga\D1-1819.csv')

understats = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\understat_per_game.csv')

In [3]:
s1819 = s1819[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR','HTHG','HTAG',
              'HS', 'AS', 'HST','AST','HC','AC', 'HF', 'AF', 'B365H', 'B365A', 'B365D',
               'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']].reset_index(drop=True)

In [4]:
s1819.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,B365D,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA
0,24/08/2018,Bayern Munich,Hoffenheim,3,1,H,1,0,16,8,...,7.50,1.20,7.86,14.90,1.17,8.00,13.00,1.20,7.5,15.0
1,25/08/2018,Fortuna Dusseldorf,Augsburg,1,2,A,1,0,9,14,...,3.25,2.51,3.32,3.06,2.45,3.25,2.90,2.50,3.3,3.0
2,25/08/2018,Freiburg,Ein Frankfurt,0,2,A,0,1,22,10,...,3.30,2.34,3.40,3.28,2.25,3.30,3.20,2.38,3.3,3.2
3,25/08/2018,Hertha,Nurnberg,1,0,H,1,0,10,12,...,3.40,2.05,3.43,4.06,2.05,3.40,3.60,2.05,3.4,3.8
4,25/08/2018,M'gladbach,Leverkusen,2,0,H,0,0,17,13,...,3.50,2.89,3.69,2.47,2.62,3.70,2.45,2.80,3.7,2.4

In [5]:
s1819['Date'] = pd.to_datetime(s1819['Date'],format="%d/%m/%Y")

In [6]:
understats['Date'] = pd.to_datetime(understats['date']).dt.strftime("%Y-%m-%d")
understats['Date'] = pd.to_datetime(understats['Date'])

In [7]:
understats =understats.replace({'team':{'Hamburger SV':'Hamburg','Bayer Leverkusen':'Leverkusen','Eintracht Frankfurt':'Ein Frankfurt',
                           "Borussia M.Gladbach":"M'gladbach",'Hertha Berlin':'Hertha','Mainz 05':'Mainz',
                           'Hannover 96':'Hannover','Borussia Dortmund':'Dortmund','VfB Stuttgart':'Stuttgart',
                           'FC Cologne':'FC Koln', 'RasenBallsport Leipzig':'RB Leipzig','Nuernberg':'Nurnberg',
                           'Fortuna Duesseldorf':'Fortuna Dusseldorf'}})

In [8]:
df = pd.merge(s1819,understats, how='inner',left_on=['Date','HomeTeam'],right_on=['Date','team'])

In [9]:
df.shape

(306, 57)

In [10]:
df.isnull().sum()

Date            0
HomeTeam        0
AwayTeam        0
FTHG            0
FTAG            0
FTR             0
HTHG            0
HTAG            0
HS              0
AS              0
HST             0
AST             0
HC              0
AC              0
HF              0
AF              0
B365H           0
B365A           0
B365D           0
PSH             1
PSD             1
PSA             1
WHH             0
WHD             0
WHA             0
VCH             0
VCD             0
VCA             0
league          0
year            0
h_a             0
xG              0
xGA             0
npxG            0
npxGA           0
deep            0
deep_allowed    0
scored          0
missed          0
xpts            0
result          0
date            0
wins            0
draws           0
loses           0
pts             0
npxGD           0
ppda_coef       0
ppda_att        0
ppda_def        0
oppda_coef      0
oppda_att       0
oppda_def       0
team            0
xG_diff         0
xGA_diff        0
xpts_diff       0
dtype: int64

In [11]:
df.rename(columns = {'xG':"HxG", 'xGA':'AxG','deep':'Hdeep','deep_allowed':'Adeep',
                     'ppda_coef':'Hppda_coef','oppda_coef':'Appda_coef'},inplace=True)

df = df.drop(['npxG','npxGA','scored', 'missed', 'xpts', 'result', 'wins',
              'draws', 'loses', 'pts', 'npxGD', 'ppda_att', 'ppda_def',
              'oppda_att', 'oppda_def', 'team', 'xG_diff', 'xGA_diff',
              'xpts_diff', 'date', 'year','h_a'],axis=1)

In [12]:
#We know that most of the times the books odds are almost the same. So we are going to replace the null values with the
#average of the 3 other sites odds
index = df.loc[df['PSH'].isnull()].index
    
df.loc[index,'PSH'] = (df.loc[index,'B365H'] + df.loc[index,'WHH'] + df.loc[index,'VCH'])/3
df.loc[index,'PSD'] = (df.loc[index,'B365D'] + df.loc[index,'WHD'] + df.loc[index,'VCD'])/3
df.loc[index,'PSA'] = (df.loc[index,'B365A'] + df.loc[index,'WHA'] + df.loc[index,'VCA'])/3

In [13]:
df.isnull().sum()

Date          0
HomeTeam      0
AwayTeam      0
FTHG          0
FTAG          0
FTR           0
HTHG          0
HTAG          0
HS            0
AS            0
HST           0
AST           0
HC            0
AC            0
HF            0
AF            0
B365H         0
B365A         0
B365D         0
PSH           0
PSD           0
PSA           0
WHH           0
WHD           0
WHA           0
VCH           0
VCD           0
VCA           0
league        0
HxG           0
AxG           0
Hdeep         0
Adeep         0
Hppda_coef    0
Appda_coef    0
dtype: int64

In [14]:
# Calculating the average of betting sites odd for each result
avgH = round((df['B365H'] + df['PSH'] + df['WHH'] + df['VCH'])/4,2)
avgD = round((df['B365D'] + df['PSD'] + df['WHD'] + df['VCD'])/4,2)
avgA = round((df['B365A'] + df['PSA'] + df['WHA'] + df['VCA'])/4,2)

df['AVGH'] = avgH
df['AVGD'] = avgD
df['AVGA'] = avgA

#drop the existing columns with betting odds
df = df.drop(['PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 
              'VCD', 'VCA', 'B365H', 'B365D', 'B365A'],axis=1)

In [15]:
df['season'] = '2018/2019'

In [16]:
df.head(9)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,HxG,AxG,Hdeep,Adeep,Hppda_coef,Appda_coef,AVGH,AVGD,AVGA,season
0,2018-08-24,Bayern Munich,Hoffenheim,3,1,H,1,0,16,8,...,3.08883,0.697274,11,3,9.411765,13.333333,1.19,7.72,13.72,2018/2019
1,2018-08-25,Fortuna Dusseldorf,Augsburg,1,2,A,1,0,9,14,...,1.32783,0.755029,5,4,9.444444,11.040000,2.46,3.28,2.99,2018/2019
2,2018-08-25,Freiburg,Ein Frankfurt,0,2,A,0,1,22,10,...,1.46674,0.814150,13,2,9.421053,15.866667,2.32,3.32,3.23,2018/2019
3,2018-08-25,Hertha,Nurnberg,1,0,H,1,0,10,12,...,1.03309,1.344120,4,3,11.916667,14.400000,2.05,3.41,3.80,2018/2019
4,2018-08-25,M'gladbach,Leverkusen,2,0,H,0,0,17,13,...,3.34179,1.057750,10,6,13.166667,17.625000,2.78,3.65,2.44,2018/2019
5,2018-08-25,Werder Bremen,Hannover,1,1,D,0,0,15,13,...,1.91197,0.840127,7,4,11.280000,11.960000,1.88,3.70,4.03,2018/2019
6,2018-08-25,Wolfsburg,Schalke 04,2,1,H,1,0,11,9,...,1.31029,1.861540,6,3,5.750000,9.961538,3.22,3.26,2.36,2018/2019
7,2018-08-26,Dortmund,RB Leipzig,4,1,H,3,1,10,10,...,1.96153,1.462680,4,4,10.950000,7.600000,1.76,3.96,4.46,2018/2019
8,2018-08-26,Mainz,Stuttgart,1,0,H,0,0,8,12,...,1.28621,1.078470,4,4,8.178571,14.352941,2.78,3.23,2.67,2018/2019

In [17]:
df.loc[df['HomeTeam']=='Bayern Munich','ranking_HT_ls'] = 1
df.loc[df['HomeTeam']=='Schalke 04','ranking_HT_ls'] = 2
df.loc[df['HomeTeam']=='Hoffenheim','ranking_HT_ls'] = 3
df.loc[df['HomeTeam']=='Dortmund','ranking_HT_ls'] = 4
df.loc[df['HomeTeam']=='Leverkusen','ranking_HT_ls'] = 5
df.loc[df['HomeTeam']=='RB Leipzig','ranking_HT_ls'] = 6
df.loc[df['HomeTeam']=='Stuttgart','ranking_HT_ls'] = 7
df.loc[df['HomeTeam']=='Ein Frankfurt','ranking_HT_ls'] = 8
df.loc[df['HomeTeam']=="M'gladbach",'ranking_HT_ls'] = 9
df.loc[df['HomeTeam']=='Hertha','ranking_HT_ls'] = 10
df.loc[df['HomeTeam']=='Werder Bremen','ranking_HT_ls'] = 11
df.loc[df['HomeTeam']=='Augsburg','ranking_HT_ls'] = 12
df.loc[df['HomeTeam']=='Hannover','ranking_HT_ls'] = 13
df.loc[df['HomeTeam']=='Mainz','ranking_HT_ls'] = 14
df.loc[df['HomeTeam']=='Freiburg','ranking_HT_ls'] = 15
df.loc[df['HomeTeam']=='Wolfsburg','ranking_HT_ls'] = 16
df.loc[df['HomeTeam']=='Fortuna Dusseldorf','ranking_HT_ls'] = -1
df.loc[df['HomeTeam']=='Nurnberg','ranking_HT_ls'] = -2

In [18]:
df.loc[df['AwayTeam']=='Bayern Munich','ranking_AT_ls'] = 1
df.loc[df['AwayTeam']=='Schalke 04','ranking_AT_ls'] = 2
df.loc[df['AwayTeam']=='Hoffenheim','ranking_AT_ls'] = 3
df.loc[df['AwayTeam']=='Dortmund','ranking_AT_ls'] = 4
df.loc[df['AwayTeam']=='Leverkusen','ranking_AT_ls'] = 5
df.loc[df['AwayTeam']=='RB Leipzig','ranking_AT_ls'] = 6
df.loc[df['AwayTeam']=='Stuttgart','ranking_AT_ls'] = 7
df.loc[df['AwayTeam']=='Ein Frankfurt','ranking_AT_ls'] = 8
df.loc[df['AwayTeam']=="M'gladbach",'ranking_AT_ls'] = 9
df.loc[df['AwayTeam']=='Hertha','ranking_AT_ls'] = 10
df.loc[df['AwayTeam']=='Werder Bremen','ranking_AT_ls'] = 11
df.loc[df['AwayTeam']=='Augsburg','ranking_AT_ls'] = 12
df.loc[df['AwayTeam']=='Hannover','ranking_AT_ls'] = 13
df.loc[df['AwayTeam']=='Mainz','ranking_AT_ls'] = 14
df.loc[df['AwayTeam']=='Freiburg','ranking_AT_ls'] = 15
df.loc[df['AwayTeam']=='Wolfsburg','ranking_AT_ls'] = 16
df.loc[df['AwayTeam']=='Fortuna Dusseldorf','ranking_AT_ls'] = -1
df.loc[df['AwayTeam']=='Nurnberg','ranking_AT_ls'] = -2

In [19]:
df.head(9)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,Hdeep,Adeep,Hppda_coef,Appda_coef,AVGH,AVGD,AVGA,season,ranking_HT_ls,ranking_AT_ls
0,2018-08-24,Bayern Munich,Hoffenheim,3,1,H,1,0,16,8,...,11,3,9.411765,13.333333,1.19,7.72,13.72,2018/2019,1.0,3.0
1,2018-08-25,Fortuna Dusseldorf,Augsburg,1,2,A,1,0,9,14,...,5,4,9.444444,11.040000,2.46,3.28,2.99,2018/2019,-1.0,12.0
2,2018-08-25,Freiburg,Ein Frankfurt,0,2,A,0,1,22,10,...,13,2,9.421053,15.866667,2.32,3.32,3.23,2018/2019,15.0,8.0
3,2018-08-25,Hertha,Nurnberg,1,0,H,1,0,10,12,...,4,3,11.916667,14.400000,2.05,3.41,3.80,2018/2019,10.0,-2.0
4,2018-08-25,M'gladbach,Leverkusen,2,0,H,0,0,17,13,...,10,6,13.166667,17.625000,2.78,3.65,2.44,2018/2019,9.0,5.0
5,2018-08-25,Werder Bremen,Hannover,1,1,D,0,0,15,13,...,7,4,11.280000,11.960000,1.88,3.70,4.03,2018/2019,11.0,13.0
6,2018-08-25,Wolfsburg,Schalke 04,2,1,H,1,0,11,9,...,6,3,5.750000,9.961538,3.22,3.26,2.36,2018/2019,16.0,2.0
7,2018-08-26,Dortmund,RB Leipzig,4,1,H,3,1,10,10,...,4,4,10.950000,7.600000,1.76,3.96,4.46,2018/2019,4.0,6.0
8,2018-08-26,Mainz,Stuttgart,1,0,H,0,0,8,12,...,4,4,8.178571,14.352941,2.78,3.23,2.67,2018/2019,14.0,7.0

In [20]:
df.to_csv('bundesliga-1819.csv', index=False)