In [1]:
import pandas as pd
import numpy as np

In [2]:
s1718 = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\Bundesliga\D1-1718.csv')

understats = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\understat_per_game.csv')

In [3]:
s1718 = s1718[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR','HTHG','HTAG',
              'HS', 'AS', 'HST','AST','HC','AC', 'HF', 'AF', 'B365H', 'B365A', 'B365D',
               'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']].reset_index(drop=True)

In [4]:
s1718.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,B365D,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA
0,18/08/17,Bayern Munich,Leverkusen,3,1,H,2,0,13,19,...,6.0,1.26,6.75,12.30,1.25,6.00,11.0,1.25,6.5,12.0
1,19/08/17,Hamburg,Augsburg,1,0,H,1,0,11,13,...,3.4,2.19,3.35,3.70,2.20,3.20,3.4,2.15,3.3,3.7
2,19/08/17,Hertha,Stuttgart,2,0,H,0,0,10,9,...,3.4,2.07,3.58,3.82,2.10,3.40,3.5,2.10,3.5,3.6
3,19/08/17,Hoffenheim,Werder Bremen,1,0,H,0,0,14,11,...,4.0,1.81,4.12,4.38,1.83,3.75,4.0,1.80,4.1,4.2
4,19/08/17,Mainz,Hannover,0,1,A,0,0,14,6,...,3.4,1.99,3.53,4.20,2.00,3.25,4.0,2.00,3.5,3.9

In [5]:
s1718['Date'] = pd.to_datetime(s1718['Date'],format="%d/%m/%y")

In [6]:
understats['Date'] = pd.to_datetime(understats['date']).dt.strftime("%Y-%m-%d")
understats['Date'] = pd.to_datetime(understats['Date'])

In [7]:
understats =understats.replace({'team':{'Hamburger SV':'Hamburg','Bayer Leverkusen':'Leverkusen','Eintracht Frankfurt':'Ein Frankfurt',
                           "Borussia M.Gladbach":"M'gladbach",'Hertha Berlin':'Hertha','Mainz 05':'Mainz',
                           'Hannover 96':'Hannover','Borussia Dortmund':'Dortmund','VfB Stuttgart':'Stuttgart',
                           'FC Cologne':'FC Koln', 'RasenBallsport Leipzig':'RB Leipzig','Nuernberg':'Nurnberg',
                           'Fortuna Duesseldorf':'Fortuna Dusseldorf'}})

In [8]:
df = pd.merge(s1718,understats, how='inner',left_on=['Date','HomeTeam'],right_on=['Date','team'])

In [9]:
df.shape

(306, 57)

In [10]:
df.isnull().sum()

Date            0
HomeTeam        0
AwayTeam        0
FTHG            0
FTAG            0
FTR             0
HTHG            0
HTAG            0
HS              0
AS              0
HST             0
AST             0
HC              0
AC              0
HF              0
AF              0
B365H           0
B365A           0
B365D           0
PSH             0
PSD             0
PSA             0
WHH             0
WHD             0
WHA             0
VCH             0
VCD             0
VCA             0
league          0
year            0
h_a             0
xG              0
xGA             0
npxG            0
npxGA           0
deep            0
deep_allowed    0
scored          0
missed          0
xpts            0
result          0
date            0
wins            0
draws           0
loses           0
pts             0
npxGD           0
ppda_coef       0
ppda_att        0
ppda_def        0
oppda_coef      0
oppda_att       0
oppda_def       0
team            0
xG_diff         0
xGA_diff        0
xpts_diff       0
dtype: int64

In [11]:
# Calculating the average of betting sites odd for each result
avgH = round((df['B365H'] + df['PSH'] + df['WHH'] + df['VCH'])/4,2)
avgD = round((df['B365D'] + df['PSD'] + df['WHD'] + df['VCD'])/4,2)
avgA = round((df['B365A'] + df['PSA'] + df['WHA'] + df['VCA'])/4,2)

df['AVGH'] = avgH
df['AVGD'] = avgD
df['AVGA'] = avgA

#drop the existing columns with betting odds
df = df.drop(['PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 
              'VCD', 'VCA', 'B365H', 'B365D', 'B365A'],axis=1)

In [12]:
df.rename(columns = {'xG':"HxG", 'xGA':'AxG','deep':'Hdeep','deep_allowed':'Adeep',
                     'ppda_coef':'Hppda_coef','oppda_coef':'Appda_coef'},inplace=True)

df = df.drop(['npxG','npxGA','scored', 'missed', 'xpts', 'result', 'wins',
              'draws', 'loses', 'pts', 'npxGD', 'ppda_att', 'ppda_def',
              'oppda_att', 'oppda_def', 'team', 'xG_diff', 'xGA_diff',
              'xpts_diff', 'date', 'year','h_a'],axis=1)

In [13]:
df['season'] = '2017/2018'

In [14]:
df.head(9)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,HxG,AxG,Hdeep,Adeep,Hppda_coef,Appda_coef,AVGH,AVGD,AVGA,season
0,2017-08-18,Bayern Munich,Leverkusen,3,1,H,2,0,13,19,...,2.779060,1.886600,13,14,13.090909,11.846154,1.25,6.31,11.82,2017/2018
1,2017-08-19,Hamburg,Augsburg,1,0,H,1,0,11,13,...,0.552380,0.573987,4,11,10.680000,4.583333,2.16,3.31,3.60,2017/2018
2,2017-08-19,Hertha,Stuttgart,2,0,H,0,0,10,9,...,0.436556,0.879388,1,6,8.545455,12.629630,2.07,3.47,3.70,2017/2018
3,2017-08-19,Hoffenheim,Werder Bremen,1,0,H,0,0,14,11,...,0.974270,0.806833,8,2,7.541667,15.227273,1.80,3.99,4.23,2017/2018
4,2017-08-19,Mainz,Hannover,0,1,A,0,0,14,6,...,0.526663,0.610149,6,1,4.914286,14.913043,2.00,3.42,4.02,2017/2018
5,2017-08-19,Schalke 04,RB Leipzig,2,0,H,1,0,11,12,...,1.912330,0.791215,3,5,9.558824,4.476190,2.82,3.37,2.55,2017/2018
6,2017-08-19,Wolfsburg,Dortmund,0,3,A,0,2,9,13,...,0.495065,1.124240,2,10,19.111111,3.093750,4.01,3.97,1.84,2017/2018
7,2017-08-20,Freiburg,Ein Frankfurt,0,0,D,0,0,7,15,...,0.231368,1.542960,3,5,10.823529,10.566667,2.50,3.26,2.98,2017/2018
8,2017-08-20,M'gladbach,FC Koln,1,0,H,0,0,22,13,...,1.625030,0.837903,10,4,14.181818,15.727273,1.94,3.56,4.06,2017/2018

In [15]:
df.loc[df['HomeTeam']=='Bayern Munich','ranking_HT_ls'] = 1
df.loc[df['HomeTeam']=='RB Leipzig','ranking_HT_ls'] = 2
df.loc[df['HomeTeam']=='Dortmund','ranking_HT_ls'] = 3
df.loc[df['HomeTeam']=='Hoffenheim','ranking_HT_ls'] = 4
df.loc[df['HomeTeam']=='FC Koln','ranking_HT_ls'] = 5
df.loc[df['HomeTeam']=='Hertha','ranking_HT_ls'] = 6
df.loc[df['HomeTeam']=='Freiburg','ranking_HT_ls'] = 7
df.loc[df['HomeTeam']=='Werder Bremen','ranking_HT_ls'] = 8
df.loc[df['HomeTeam']=="M'gladbach",'ranking_HT_ls'] = 9
df.loc[df['HomeTeam']=='Schalke 04','ranking_HT_ls'] = 10
df.loc[df['HomeTeam']=='Ein Frankfurt','ranking_HT_ls'] = 11
df.loc[df['HomeTeam']=='Leverkusen','ranking_HT_ls'] = 12
df.loc[df['HomeTeam']=='Augsburg','ranking_HT_ls'] = 13
df.loc[df['HomeTeam']=='Hamburg','ranking_HT_ls'] = 14
df.loc[df['HomeTeam']=='Mainz','ranking_HT_ls'] = 15
df.loc[df['HomeTeam']=='Wolfsburg','ranking_HT_ls'] = 16
df.loc[df['HomeTeam']=='Stuttgart','ranking_HT_ls'] = -1
df.loc[df['HomeTeam']=='Hannover','ranking_HT_ls'] = -2

In [16]:
df.loc[df['AwayTeam']=='Bayern Munich','ranking_AT_ls'] = 1
df.loc[df['AwayTeam']=='RB Leipzig','ranking_AT_ls'] = 2
df.loc[df['AwayTeam']=='Dortmund','ranking_AT_ls'] = 3
df.loc[df['AwayTeam']=='Hoffenheim','ranking_AT_ls'] = 4
df.loc[df['AwayTeam']=='FC Koln','ranking_AT_ls'] = 5
df.loc[df['AwayTeam']=='Hertha','ranking_AT_ls'] = 6
df.loc[df['AwayTeam']=='Freiburg','ranking_AT_ls'] = 7
df.loc[df['AwayTeam']=='Werder Bremen','ranking_AT_ls'] = 8
df.loc[df['AwayTeam']=="M'gladbach",'ranking_AT_ls'] = 9
df.loc[df['AwayTeam']=='Schalke 04','ranking_AT_ls'] = 10
df.loc[df['AwayTeam']=='Ein Frankfurt','ranking_AT_ls'] = 11
df.loc[df['AwayTeam']=='Leverkusen','ranking_AT_ls'] = 12
df.loc[df['AwayTeam']=='Augsburg','ranking_AT_ls'] = 13
df.loc[df['AwayTeam']=='Hamburg','ranking_AT_ls'] = 14
df.loc[df['AwayTeam']=='Mainz','ranking_AT_ls'] = 15
df.loc[df['AwayTeam']=='Wolfsburg','ranking_AT_ls'] = 16
df.loc[df['AwayTeam']=='Stuttgart','ranking_AT_ls'] = -1
df.loc[df['AwayTeam']=='Hannover','ranking_AT_ls'] = -2

In [17]:
df.head(9)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,...,Hdeep,Adeep,Hppda_coef,Appda_coef,AVGH,AVGD,AVGA,season,ranking_HT_ls,ranking_AT_ls
0,2017-08-18,Bayern Munich,Leverkusen,3,1,H,2,0,13,19,...,13,14,13.090909,11.846154,1.25,6.31,11.82,2017/2018,1.0,12.0
1,2017-08-19,Hamburg,Augsburg,1,0,H,1,0,11,13,...,4,11,10.680000,4.583333,2.16,3.31,3.60,2017/2018,14.0,13.0
2,2017-08-19,Hertha,Stuttgart,2,0,H,0,0,10,9,...,1,6,8.545455,12.629630,2.07,3.47,3.70,2017/2018,6.0,-1.0
3,2017-08-19,Hoffenheim,Werder Bremen,1,0,H,0,0,14,11,...,8,2,7.541667,15.227273,1.80,3.99,4.23,2017/2018,4.0,8.0
4,2017-08-19,Mainz,Hannover,0,1,A,0,0,14,6,...,6,1,4.914286,14.913043,2.00,3.42,4.02,2017/2018,15.0,-2.0
5,2017-08-19,Schalke 04,RB Leipzig,2,0,H,1,0,11,12,...,3,5,9.558824,4.476190,2.82,3.37,2.55,2017/2018,10.0,2.0
6,2017-08-19,Wolfsburg,Dortmund,0,3,A,0,2,9,13,...,2,10,19.111111,3.093750,4.01,3.97,1.84,2017/2018,16.0,3.0
7,2017-08-20,Freiburg,Ein Frankfurt,0,0,D,0,0,7,15,...,3,5,10.823529,10.566667,2.50,3.26,2.98,2017/2018,7.0,11.0
8,2017-08-20,M'gladbach,FC Koln,1,0,H,0,0,22,13,...,10,4,14.181818,15.727273,1.94,3.56,4.06,2017/2018,9.0,5.0

In [18]:
df.to_csv('bundesliga-1718.csv', index=False)