In [1]:
import numpy as np
import pandas as pd

In [2]:
s1920 = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\Premier League\Season 2019-2020.csv')

understats = pd.read_csv(r'C:\Users\George\Desktop\football-match-prediction-using-ml-techniques\data\understat_per_game.csv')

In [3]:
s1920 = s1920[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG','HTHG','HTAG', 'FTR',
              'HS', 'AS', 'HST','AST','HC','AC', 'HF', 'AF', 'B365H', 'B365A', 'B365D',
               'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA']].reset_index(drop=True)

In [5]:
s1920.shape

(380, 28)

In [6]:
s1920.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,FTR,HS,AS,...,B365D,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA
0,09/08/2019,Liverpool,Norwich,4,1,4,0,H,15,12,...,10.00,1.15,9.59,18.05,1.12,8.5,21.00,1.14,9.5,23.00
1,10/08/2019,West Ham,Man City,0,5,0,1,A,5,14,...,6.50,11.68,6.53,1.26,13.00,6.0,1.24,12.00,6.5,1.25
2,10/08/2019,Bournemouth,Sheffield United,1,1,0,0,D,13,8,...,3.60,2.04,3.57,3.90,2.00,3.5,3.80,2.00,3.6,4.00
3,10/08/2019,Burnley,Southampton,3,0,0,0,H,10,11,...,3.20,2.71,3.31,2.81,2.70,3.2,2.75,2.70,3.3,2.80
4,10/08/2019,Crystal Palace,Everton,0,0,0,0,D,6,10,...,3.25,3.21,3.37,2.39,3.10,3.3,2.35,3.20,3.3,2.45

In [8]:
s1920['Date'] = pd.to_datetime(s1920['Date'],format="%d/%m/%Y")

In [9]:
understats['Date'] = pd.to_datetime(understats['date']).dt.strftime("%Y-%m-%d")
understats['Date'] = pd.to_datetime(understats['Date'])

In [10]:
understats =understats.replace({'team':{'Aston Villa':'Aston Villa',
       'Everton':'Everton', 'Southampton':'Southampton', 'Leicester':'Leicester', 'West Bromwich Albion':'West Brom',
       'Sunderland':'Sunderland', 'Crystal Palace':'Crystal Palace', 'Chelsea':'Chelsea', 'West Ham':'West Ham', 'Tottenham':'Tottenham',
       'Arsenal':'Arsenal', 'Swansea':'Swansea', 'Stoke':'Stoke', 'Newcastle United':'Newcastle', 'Liverpool':'Liverpool',
       'Manchester City':'Man City', 'Manchester United':'Man United', 'Hull':'Hull', 'Burnley':'Burnley',
       'Queens Park Rangers':'QPR', 'Bournemouth':'Bournemouth', 'Norwich':'Norwich', 'Watford':'Watford',
       'Middlesbrough':'Middlesbrough', 'Huddersfield':'Huddersfield', 'Brighton':'Brighton', 'Cardiff':'Cardiff', 'Fulham':'Fulham',
       'Wolverhampton Wanderers':'Wolves'}})

In [12]:
df = pd.merge(s1920,understats, how='left',left_on=['Date','HomeTeam'],right_on=['Date','team'])

In [13]:
df.isnull().sum()

Date            0
HomeTeam        0
AwayTeam        0
FTHG            0
FTAG            0
HTHG            0
HTAG            0
FTR             0
HS              0
AS              0
HST             0
AST             0
HC              0
AC              0
HF              0
AF              0
B365H           0
B365A           0
B365D           0
PSH             0
PSD             0
PSA             0
WHH             0
WHD             0
WHA             0
VCH             0
VCD             0
VCA             0
league          0
year            0
h_a             0
xG              0
xGA             0
npxG            0
npxGA           0
deep            0
deep_allowed    0
scored          0
missed          0
xpts            0
result          0
date            0
wins            0
draws           0
loses           0
pts             0
npxGD           0
ppda_coef       0
ppda_att        0
ppda_def        0
oppda_coef      0
oppda_att       0
oppda_def       0
team            0
xG_diff         0
xGA_diff        0
xpts_diff       0
dtype: int64

In [14]:
df.rename(columns = {'xG':"HxG", 'xGA':'AxG','deep':'Hdeep','deep_allowed':'Adeep',
                     'ppda_coef':'Hppda_coef','oppda_coef':'Appda_coef'},inplace=True)

df = df.drop(['npxG','npxGA','scored', 'missed', 'xpts', 'result', 'wins',
              'draws', 'loses', 'pts', 'npxGD', 'ppda_att', 'ppda_def',
              'oppda_att', 'oppda_def', 'team', 'xG_diff', 'xGA_diff',
              'xpts_diff', 'date', 'year','h_a'],axis=1)

In [15]:
# Calculating the average of betting sites odd for each result
avgH = round((df['B365H'] + df['PSH'] + df['WHH'] + df['VCH'])/4,2)
avgD = round((df['B365D'] + df['PSD'] + df['WHD'] + df['VCD'])/4,2)
avgA = round((df['B365A'] + df['PSA'] + df['WHA'] + df['VCA'])/4,2)

df['AVGH'] = avgH
df['AVGD'] = avgD
df['AVGA'] = avgA

#drop the existing columns with betting odds
df = df.drop(['PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 
              'VCD', 'VCA', 'B365H', 'B365D', 'B365A'],axis=1)

In [16]:
df['season'] = '2019/2020'

In [17]:
df.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,FTR,HS,AS,...,HxG,AxG,Hdeep,Adeep,Hppda_coef,Appda_coef,AVGH,AVGD,AVGA,season
0,2019-08-09,Liverpool,Norwich,4,1,4,0,H,15,12,...,2.234560,0.842407,11,5,5.942857,21.454545,1.14,9.40,20.26,2019/2020
1,2019-08-10,West Ham,Man City,0,5,0,1,A,5,14,...,1.200300,3.183770,1,9,16.400000,6.935484,12.17,6.38,1.24,2019/2020
2,2019-08-10,Bournemouth,Sheffield United,1,1,0,0,D,13,8,...,1.340990,1.598640,4,6,13.600000,9.133333,2.00,3.57,3.82,2019/2020
3,2019-08-10,Burnley,Southampton,3,0,0,0,H,10,11,...,0.909241,1.087520,0,9,9.277778,5.500000,2.68,3.25,2.78,2019/2020
4,2019-08-10,Crystal Palace,Everton,0,0,0,0,D,6,10,...,0.871590,1.224600,5,5,11.307692,4.074074,3.13,3.30,2.39,2019/2020

In [18]:
df.to_csv('epl-1920.csv', index=False)